CFLAGS=-Wall -Wextra -Werror 
strlen_tests:
	gcc $(CFLAGS) -o Quest_1 s21_string.c s21_string_test.c strlenmain.c
	mv Quest_1 ../build
	rm -rf *.o
strcmp_tests:
	gcc $(CFLAGS) -o Quest_2 s21_string.c s21_string_test.c strcmpmain.c
	mv Quest_2 ../build
	rm -rf *.o
strcpy_tests:
	gcc $(CFLAGS) -o Quest_3 s21_string.c s21_string_test.c strcpymain.c
	mv Quest_3 ../build
	rm -rf *.o
strcat_tests:
	gcc $(CFLAGS) -o Quest_4 s21_string.c s21_string_test.c strcatmain.c
	mv Quest_4 ../build
	rm -rf *.o
strchr_tests:
	gcc $(CFLAGS) -o Quest_5 s21_string.c s21_string_test.c strchrmain.c
	mv Quest_5 ../build
	rm -rf *.o
strstr_tests:
	gcc $(CFLAGS) -o Quest_6 s21_string.c s21_string_test.c strstrmain.c
	mv Quest_6 ../build
	rm -rf *.o

