CFLAGS=gcc -Wall -Wextra -Werror -o

print_module:
	$(CFLAGS) Quest_1 main_module_entry_point.c print_module.c 
	mv Quest_1 ../build
documentation_module:
	$(CFLAGS) Quest_2 main_module_entry_point.c print_module.c documentation_module.c 
	mv Quest_2 ../build
bst_create_test:
	$(CFLAGS) Quest_3 bst.c bst_create_test.c 
	mv Quest_3 ../build
bst_insert_test:
	$(CFLAGS) Quest_4 bst.c bst_insert_test.c 
	mv Quest_4 ../build
bst_traverse_test:
	$(CFLAGS) Quest_5 bst.c bst_traverse_test.c 
	mv Quest_5 ../build